"""
SQLite database models for Stock Sentiment Bot.
Uses SQLAlchemy ORM for clean data access.
"""
from datetime import datetime
from typing import Optional
from sqlalchemy import (
    create_engine,
    Column,
    Integer,
    Float,
    String,
    DateTime,
    Boolean,
    Text,
    ForeignKey,
    Index,
)
from sqlalchemy.orm import declarative_base, relationship, sessionmaker
from sqlalchemy.pool import StaticPool

Base = declarative_base()


class Trade(Base):
    """Record of executed trades."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Trade identification
    ticker = Column(String(10), nullable=False, index=True)
    order_id = Column(String(50), unique=True)

    # Entry details
    entry_time = Column(DateTime, nullable=False, default=datetime.utcnow)
    entry_price = Column(Float, nullable=False)
    quantity = Column(Float, nullable=False)
    side = Column(String(10), nullable=False)  # 'buy' or 'sell'

    # Position sizing
    risk_percent = Column(Float, nullable=False)  # % of account risked
    stop_loss = Column(Float)
    take_profit_1 = Column(Float)
    take_profit_2 = Column(Float)
    take_profit_3 = Column(Float)

    # Exit details (filled when closed)
    exit_time = Column(DateTime)
    exit_price = Column(Float)
    exit_reason = Column(String(50))  # 'stop_loss', 'take_profit', 'manual', etc.

    # P&L
    realized_pnl = Column(Float)
    realized_pnl_percent = Column(Float)

    # Signal that triggered trade
    signal_score = Column(Integer)
    signal_id = Column(Integer, ForeignKey("signals.id"))
    signal = relationship("Signal", back_populates="trades")

    # Status
    status = Column(String(20), default="open")  # 'open', 'closed', 'cancelled'

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    __table_args__ = (
        Index("idx_trades_ticker_status", "ticker", "status"),
        Index("idx_trades_entry_time", "entry_time"),
    )


class Signal(Base):
    """Trading signals generated by sentiment analysis."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Signal identification
    ticker = Column(String(10), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow)

    # Signal components
    total_score = Column(Integer, nullable=False)
    sentiment_score = Column(Float)  # -1 to 1
    mention_velocity = Column(Float)  # mentions per hour
    volume_ratio = Column(Float)  # current vs average
    rsi = Column(Float)

    # Sentiment details
    reddit_mentions = Column(Integer, default=0)
    reddit_sentiment = Column(Float)  # -1 to 1
    news_mentions = Column(Integer, default=0)
    news_sentiment = Column(Float)  # -1 to 1
    unique_authors = Column(Integer, default=0)

    # Decision
    action = Column(String(10))  # 'buy', 'sell', 'hold', 'skip'
    confidence = Column(Float)
    reason = Column(Text)

    # Outcome tracking
    was_executed = Column(Boolean, default=False)
    trades = relationship("Trade", back_populates="signal")

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        Index("idx_signals_ticker_timestamp", "ticker", "timestamp"),
        Index("idx_signals_score", "total_score"),
    )


class DailyStats(Base):
    """Daily trading statistics for circuit breaker tracking."""
    __tablename__ = "daily_stats"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(DateTime, nullable=False, unique=True, index=True)

    # P&L
    starting_balance = Column(Float, nullable=False)
    ending_balance = Column(Float)
    daily_pnl = Column(Float, default=0)
    daily_pnl_percent = Column(Float, default=0)

    # Trade counts
    trades_executed = Column(Integer, default=0)
    trades_won = Column(Integer, default=0)
    trades_lost = Column(Integer, default=0)

    # Risk metrics
    max_drawdown = Column(Float, default=0)
    consecutive_losses = Column(Integer, default=0)

    # Circuit breaker status
    daily_loss_limit_hit = Column(Boolean, default=False)
    trade_limit_hit = Column(Boolean, default=False)
    drawdown_halt = Column(Boolean, default=False)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class SentimentCache(Base):
    """Cache for sentiment data to avoid repeated API calls."""
    __tablename__ = "sentiment_cache"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String(10), nullable=False, index=True)
    source = Column(String(20), nullable=False)  # 'reddit', 'news'
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow)

    # Cached data
    mentions = Column(Integer, default=0)
    sentiment = Column(Float)  # -1 to 1
    unique_authors = Column(Integer, default=0)
    top_posts = Column(Text)  # JSON array of top post titles
    raw_data = Column(Text)  # Full JSON for debugging

    # Cache validity
    expires_at = Column(DateTime, nullable=False)

    __table_args__ = (
        Index("idx_cache_ticker_source", "ticker", "source"),
        Index("idx_cache_expires", "expires_at"),
    )


class AccountSnapshot(Base):
    """Historical account balance snapshots for drawdown calculation."""
    __tablename__ = "account_snapshots"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)

    # Account values
    equity = Column(Float, nullable=False)
    cash = Column(Float, nullable=False)
    buying_power = Column(Float)

    # High water mark tracking
    high_water_mark = Column(Float, nullable=False)
    drawdown = Column(Float, default=0)
    drawdown_percent = Column(Float, default=0)

    # Position summary
    open_positions = Column(Integer, default=0)
    total_exposure = Column(Float, default=0)


class Watchlist(Base):
    """Tracked tickers for sentiment monitoring."""
    __tablename__ = "watchlist"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String(10), nullable=False, unique=True, index=True)
    sector = Column(String(50))

    # Monitoring settings
    is_active = Column(Boolean, default=True)
    priority = Column(Integer, default=1)  # 1=high, 2=medium, 3=low

    # Stats
    total_signals = Column(Integer, default=0)
    total_trades = Column(Integer, default=0)
    win_rate = Column(Float)

    # Timestamps
    added_at = Column(DateTime, default=datetime.utcnow)
    last_signal_at = Column(DateTime)


# Database initialization
def init_db(db_path: str = "data/sentiment_bot.db") -> sessionmaker:
    """Initialize database and return session maker."""
    engine = create_engine(
        f"sqlite:///{db_path}",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
        echo=False
    )

    Base.metadata.create_all(engine)

    Session = sessionmaker(bind=engine)
    return Session


def get_session(db_path: str = "data/sentiment_bot.db"):
    """Get a database session."""
    Session = init_db(db_path)
    return Session()
